/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Enum.java to edit this template
 */
package operation;

/**
 *
 * @author Laza Laki Lakosta
 */
public enum Operation {
    LOGIN,SAVE_PACIJENT,SAVE_TERMIN_PREGLEDA,GET_ALL_PACIJENTE,GET_ALL_NAOCARE,SAVE_NAOCARE,GET_ALL_OPTICAR,GET_ALL_STAVKE_PREGLEDA,MAX_ID_TERMIN_PREGLEDA,MAX_ID_USLUGA
    ,UPDATE_NAOCARE,DELETE_NAOCARE,UPDATE_PACIJENTI,DELETE_PACIJENT,DELETE_TERMIN_PREGLEDA,GET_ALL_TERMIN_PREGLEDA,SAVE_USLUGA,SAVE_STATISTIKA_OD_USLUGA
    ,GET_ALL_USLUGE,GET_ALL_STATISTIKA_OD_USLUGA,DELETE_USLUGA,DELETE_STATISTIKA_OD_USLUGE,VRATI_PACIJENTE_IME_PREZIME
    ,GET_ALL_STAKLA,UPDATE_STAKLA,DELETE_STAKLA,SAVE_STAKLA,SAVE_VRSTA_USLUGE,GET_ALL_VRSTA_USLUGE,DELETE_VRSTA_USLUGE,UPDATE_VRSTA_USLUGE,KRAJ_RADA_KORISNIKA,KRAJ_RADA_LOGIN,
    VRATI_TERMIN_PREGLEDA_ID,VRATI_STAVKE_PREGLEDA_ID,DELETE_STAVKE_PREGLEDA,VRATI_USLUGA_NAOCARA_ID,VRATI_USLUGA_STAKLA_ID,VRATI_USLUGA_VRSTE_USLUGA_ID,VRATI_STATISTIKA_OD_USLUGA_ID;
}
