/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form;

import domain.Administrator;
import domain.Pacijent;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import server.Server;
import table.AdminTableModel;

/**
 *
 * @author LENOVO
 */
public class FormActiveUsers extends javax.swing.JDialog {

    /**
     * Creates new form FrmActiveUsers
     */
    private static List<Administrator> users;
    Server server;

    public FormActiveUsers(java.awt.Frame parent, boolean modal, Server server) {
        super(parent, modal);
        initComponents();
        this.server=server;
        //prepareView();
        listeForClients();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        users = server.getActiveUsers();
        System.out.println(users);
        tbl.setModel(new AdminTableModel(users));
    }
    
    private void listeForClients(){
        new Thread(new Runnable() {
            @Override
            public void run() {
                while(true){
                try {
                    System.out.println("radi");
                    prepareView();
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(FormActiveUsers.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            }
        }).start();
    }
}
