package form;

import domain.VrsteUsluga;
import java.awt.event.ActionListener;
import java.net.Socket;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenuItem;



public class FormMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    Socket socket = null;
    public FormMain() {
        super("Projekat PS - Pocetna forma");
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCurrentUser = new javax.swing.JLabel();
        btnKraj = new javax.swing.JButton();
        jmenuBarMain = new javax.swing.JMenuBar();
        jmenuProduct = new javax.swing.JMenu();
        jmiDodajPacijenta = new javax.swing.JMenuItem();
        jmiPrikaziPacijente = new javax.swing.JMenuItem();
        jmenuInvoice = new javax.swing.JMenu();
        jmiDodajNaocare = new javax.swing.JMenuItem();
        jmiPrikaziNaocare = new javax.swing.JMenuItem();
        jmenuInvoice1 = new javax.swing.JMenu();
        jmiDodajStakla = new javax.swing.JMenuItem();
        jmiPrikaziStakla = new javax.swing.JMenuItem();
        jmenuInvoice2 = new javax.swing.JMenu();
        jmiDodajVrstaUsluge = new javax.swing.JMenuItem();
        jmiPrikaziVrstaUsluge = new javax.swing.JMenuItem();
        jmenuInvoice3 = new javax.swing.JMenu();
        jmiDodajVrstaTerminPregleda = new javax.swing.JMenuItem();
        jmiPrikaziTerminPregleda = new javax.swing.JMenuItem();
        jmenuAbout = new javax.swing.JMenu();
        jmiAboutSoftware = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCurrentUser.setText("jLabel1");

        btnKraj.setText("Kraj rada");

        jmenuProduct.setText("Pacijenti");
        jmenuProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuProductActionPerformed(evt);
            }
        });

        jmiDodajPacijenta.setText("New");
        jmiDodajPacijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDodajPacijentaActionPerformed(evt);
            }
        });
        jmenuProduct.add(jmiDodajPacijenta);

        jmiPrikaziPacijente.setText("Show all");
        jmiPrikaziPacijente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPrikaziPacijenteActionPerformed(evt);
            }
        });
        jmenuProduct.add(jmiPrikaziPacijente);

        jmenuBarMain.add(jmenuProduct);

        jmenuInvoice.setText("Naocare");
        jmenuInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuInvoiceActionPerformed(evt);
            }
        });

        jmiDodajNaocare.setText("New");
        jmiDodajNaocare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDodajNaocareActionPerformed(evt);
            }
        });
        jmenuInvoice.add(jmiDodajNaocare);

        jmiPrikaziNaocare.setText("Show all");
        jmiPrikaziNaocare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPrikaziNaocareActionPerformed(evt);
            }
        });
        jmenuInvoice.add(jmiPrikaziNaocare);

        jmenuBarMain.add(jmenuInvoice);

        jmenuInvoice1.setText("Stakla");
        jmenuInvoice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuInvoice1ActionPerformed(evt);
            }
        });

        jmiDodajStakla.setText("New");
        jmiDodajStakla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDodajStaklaActionPerformed(evt);
            }
        });
        jmenuInvoice1.add(jmiDodajStakla);

        jmiPrikaziStakla.setText("Show all");
        jmiPrikaziStakla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPrikaziStaklaActionPerformed(evt);
            }
        });
        jmenuInvoice1.add(jmiPrikaziStakla);

        jmenuBarMain.add(jmenuInvoice1);

        jmenuInvoice2.setText("Vrsta Usluge");
        jmenuInvoice2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuInvoice2ActionPerformed(evt);
            }
        });

        jmiDodajVrstaUsluge.setText("New");
        jmiDodajVrstaUsluge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDodajVrstaUslugeActionPerformed(evt);
            }
        });
        jmenuInvoice2.add(jmiDodajVrstaUsluge);

        jmiPrikaziVrstaUsluge.setText("Show all");
        jmiPrikaziVrstaUsluge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPrikaziVrstaUslugeActionPerformed(evt);
            }
        });
        jmenuInvoice2.add(jmiPrikaziVrstaUsluge);

        jmenuBarMain.add(jmenuInvoice2);

        jmenuInvoice3.setText("Termin pregleda");
        jmenuInvoice3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuInvoice3ActionPerformed(evt);
            }
        });

        jmiDodajVrstaTerminPregleda.setText("New");
        jmiDodajVrstaTerminPregleda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDodajVrstaTerminPregledaActionPerformed(evt);
            }
        });
        jmenuInvoice3.add(jmiDodajVrstaTerminPregleda);

        jmiPrikaziTerminPregleda.setText("Show all");
        jmiPrikaziTerminPregleda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPrikaziTerminPregledaActionPerformed(evt);
            }
        });
        jmenuInvoice3.add(jmiPrikaziTerminPregleda);

        jmenuBarMain.add(jmenuInvoice3);

        jmenuAbout.setText("About");

        jmiAboutSoftware.setText("Software");
        jmenuAbout.add(jmiAboutSoftware);

        jmenuBarMain.add(jmenuAbout);

        setJMenuBar(jmenuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCurrentUser, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnKraj))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCurrentUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                .addComponent(btnKraj)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmenuProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuProductActionPerformed
    }//GEN-LAST:event_jmenuProductActionPerformed

    private void jmenuInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuInvoiceActionPerformed
      
    }//GEN-LAST:event_jmenuInvoiceActionPerformed

    private void jmiDodajPacijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDodajPacijentaActionPerformed
       //new PacijentForm().setVisible(true);
    }//GEN-LAST:event_jmiDodajPacijentaActionPerformed

    private void jmiDodajNaocareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDodajNaocareActionPerformed
        //new NaocareForm().setVisible(true);
    }//GEN-LAST:event_jmiDodajNaocareActionPerformed

    private void jmiPrikaziPacijenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPrikaziPacijenteActionPerformed
        //new PacijentiViewForm(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jmiPrikaziPacijenteActionPerformed

    private void jmiDodajStaklaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDodajStaklaActionPerformed
        //new StaklaForm().setVisible(true);
    }//GEN-LAST:event_jmiDodajStaklaActionPerformed

    private void jmenuInvoice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuInvoice1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmenuInvoice1ActionPerformed

    private void jmiPrikaziNaocareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPrikaziNaocareActionPerformed
        //new NaocareViewForm().setVisible(true);
    }//GEN-LAST:event_jmiPrikaziNaocareActionPerformed

    private void jmiPrikaziStaklaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPrikaziStaklaActionPerformed
        //new StaklaViewForm(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jmiPrikaziStaklaActionPerformed

    private void jmiDodajVrstaUslugeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDodajVrstaUslugeActionPerformed
        //new VrstaUslugeForm().setVisible(true);
    }//GEN-LAST:event_jmiDodajVrstaUslugeActionPerformed

    private void jmiPrikaziVrstaUslugeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPrikaziVrstaUslugeActionPerformed
        //new VrstaUslugeViewForm().setVisible(true);
    }//GEN-LAST:event_jmiPrikaziVrstaUslugeActionPerformed

    private void jmenuInvoice2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuInvoice2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmenuInvoice2ActionPerformed

    private void jmiDodajVrstaTerminPregledaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDodajVrstaTerminPregledaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiDodajVrstaTerminPregledaActionPerformed

    private void jmiPrikaziTerminPregledaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPrikaziTerminPregledaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiPrikaziTerminPregledaActionPerformed

    private void jmenuInvoice3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuInvoice3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmenuInvoice3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKraj;
    private javax.swing.JMenu jmenuAbout;
    private javax.swing.JMenuBar jmenuBarMain;
    private javax.swing.JMenu jmenuInvoice;
    private javax.swing.JMenu jmenuInvoice1;
    private javax.swing.JMenu jmenuInvoice2;
    private javax.swing.JMenu jmenuInvoice3;
    private javax.swing.JMenu jmenuProduct;
    private javax.swing.JMenuItem jmiAboutSoftware;
    private javax.swing.JMenuItem jmiDodajNaocare;
    private javax.swing.JMenuItem jmiDodajPacijenta;
    private javax.swing.JMenuItem jmiDodajStakla;
    private javax.swing.JMenuItem jmiDodajVrstaTerminPregleda;
    private javax.swing.JMenuItem jmiDodajVrstaUsluge;
    private javax.swing.JMenuItem jmiPrikaziNaocare;
    private javax.swing.JMenuItem jmiPrikaziPacijente;
    private javax.swing.JMenuItem jmiPrikaziStakla;
    private javax.swing.JMenuItem jmiPrikaziTerminPregleda;
    private javax.swing.JMenuItem jmiPrikaziVrstaUsluge;
    private javax.swing.JLabel lblCurrentUser;
    // End of variables declaration//GEN-END:variables

    public void jmiDodajPacijentaAddActionListener(ActionListener actionListener){
        jmiDodajPacijenta.addActionListener(actionListener);
    }
    public void jmiPretraziPacijentaAddActionListener(ActionListener actionListener){
        jmiPrikaziPacijente.addActionListener(actionListener);
    }
    public void jmiDodajNaocareAddActionListener(ActionListener actionListener){
        jmiDodajNaocare.addActionListener(actionListener);
    }
    public void jmiPretraziNaocareAddActionListener(ActionListener actionListener){
        jmiPrikaziNaocare.addActionListener(actionListener);
    }
    public void jmiDodajStaklaAddActionListener(ActionListener actionListener){
        jmiDodajStakla.addActionListener(actionListener);
    }
    public void jmiPretraziStaklaAddActionListener(ActionListener actionListener){
        jmiPrikaziStakla.addActionListener(actionListener);
    }
    public void jmiDodajVrsteUslugaAddActionListener(ActionListener actionListener){
        jmiDodajVrstaUsluge.addActionListener(actionListener);
    }
    public void jmiPretraziVrsteUslugaAddActionListener(ActionListener actionListener){
        jmiPrikaziVrstaUsluge.addActionListener(actionListener);
    }
    public void jmiSoftverAddActionListener(ActionListener actionListener) {
        jmiAboutSoftware.addActionListener(actionListener);
    }
    public void addKrajBtnAddActionListener(ActionListener actionListener) {
        btnKraj.addActionListener(actionListener);
    }
    public void jmiPretraziVrsteTerminPregledaAddActionListener(ActionListener actionListener){
        jmiDodajVrstaTerminPregleda.addActionListener(actionListener);
    }
    public void jmiPrikaziTerminPregledaAddActionListener(ActionListener actionListener) {                                                       
        jmiPrikaziTerminPregleda.addActionListener(actionListener);
    } 
//    
//    public JLabel getLabelaUlogovaniKorisnik() {
//        return labelaUlogovaniKorisnik;
//    }
}
